### ISSUE TITLE
Bind option for flame (source IP address)

### ISSUE THREAD

**Issue by SrX** [DNS-OARC/flamethrower#25]
Hi! 
I would like to ask for the option to bind to source IP address at flame.
This feature could be useful to simulate the traffic of several clients in the same host.

Regards,

**Comment by shane-kerr** [comment]
I think this is a good idea.

**Comment by weyrick** [comment]
Yes, and should be a pretty simple change - I think it just needs a command line item for the IP to bind to, a matching TrafGenConfig item, and updates to `TrafGen::start_udp` and `TrafGen::start_tcp` to bind to requested IP. Would be happy to help review a patch, otherwise we can put it on the backlog waiting for cycles.

**Comment by yantarou** [comment]
I'd like to have this feature too, thus created a PR for review:

https://github.com/DNS-OARC/flamethrower/pull/32

**Comment by weyrick** [comment]
merged #32. Thanks!
