### ISSUE TITLE
generator error: unable to open the file

### ISSUE THREAD

**Issue by aiys0211** [DNS-OARC/flamethrower#38]
Hi @weyrick ,
   When I execute "docker run aiys0211/flamethrower_v0.10.2 -c 50 -q 200 -p 853 -l 10 -t 3 -f 2.txt -P dot 192.168.1.6", it prompts that "generator error: unable to open 2.txt"
![1](https://user-images.githubusercontent.com/30883151/77923644-4e91cd00-72d5-11ea-9d2b-d3da4025aa4e.png)

   version:Flamethrower 0.11.0
   cat 2.txt:
www.google.com A
www.bing.com    A
www.bing.cn A
www.baidu.cn    cname
www.zhutianwei.cn   A
zhutianwei.cn   NS
3evip.cn    MX
pop3.3evip.cn   cname
www.slimsmart.cn    A
slimsmart.cn    NS
www.7k9.cn  A
test.7k9.cn A
pi.net A

**Comment by vfrazao-ns1** [comment]
@aiys0211 it looks like it is failing because the application cannot access the file. You should try mounting the file into the container in your run command (see: https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only).

In your case something like this might work:
`docker run -v $PWD/2.txt:/2.txt aiys0211/flamethrower_v0.10.2 -c 50 -q 200 -p 853 -l 10 -t 3 -f 2.txt -P dot 192.168.1.6`

**Comment by aiys0211** [comment]
I just started using docker last week, many functions are not familiar, thank you very much~
